(()=>{
const KEY='quick-add-store-v2',SUB=['AWL','BE','BWPP','DFP','ECM','ITS','PB','DUK'];
const root=document.getElementById('learn');if(!root)return;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function all(){try{const a=JSON.parse(localStorage.getItem(KEY)||'[]');return Array.isArray(a)?a:[]}catch{return[]}}
function tasks(subject){return all().filter(x=>x.type==='task'&&(!subject||x.subject===subject))}
function nextDate(subject){const a=tasks(subject).filter(x=>x.date).sort((a,b)=>a.date.localeCompare(b.date));const t=a.find(x=>new Date(x.date+'T23:59')>=new Date())||a[a.length-1];return t?.date?`${t.date.split('-').reverse().join('.')} · ${t.title}`:'Noch kein Termin.'}
function buildQuestions(subject){const qs=[];tasks(subject).forEach(t=>{if(t.practiceQuestions?.length)t.practiceQuestions.forEach(x=>qs.push({q:x.q,a:x.a||'',source:t.title}));else if(t.legacyQuestions?.length)t.legacyQuestions.forEach((q,i)=>qs.push({q,a:t.legacyAnswers?.[i]||'',source:t.title}));else{(t.checks||[]).forEach(ch=>{const text=ch.text.replace(/^(beschreibe|erkläre|definiere)\s+/i,'');qs.push({q:`Erkläre: ${text}`,a:t.description||'Vergleiche deine Antwort mit dem gespeicherten Lernstoff.',source:t.title})});if(t.description)qs.push({q:`Fasse „${t.title}“ in eigenen Worten zusammen.`,a:t.description,source:t.title})}});return qs}
const style=document.createElement('style');style.textContent=`.learn-sync-box{margin:16px 0;padding:16px;border:1px solid rgba(116,82,180,.2);border-radius:16px;background:rgba(255,255,255,.45)}.learn-sync-head{display:flex;justify-content:space-between;gap:10px;align-items:center;flex-wrap:wrap}.learn-sync-items{display:grid;gap:8px;margin-top:10px}.learn-sync-item{padding:10px 12px;border-radius:11px;background:rgba(126,92,190,.08)}.learn-sync-notes{margin-top:8px;padding-left:18px}.learn-test-q{padding:13px 0;border-bottom:1px solid rgba(116,82,180,.14)}.learn-test-answer{display:none;margin-top:8px;padding:10px;border-radius:10px;background:rgba(255,255,255,.65)}.learn-test-answer.open{display:block}`;document.head.appendChild(style);
function ensureBox(){let box=document.getElementById('learnAssignmentSync');if(!box){box=document.createElement('div');box.id='learnAssignmentSync';box.className='learn-sync-box';const packages=document.getElementById('studyPackages');packages?.parentElement?.appendChild(box)}return box}
function renderSubject(subject){const ts=tasks(subject),box=ensureBox();if(box)box.innerHTML=`<div class="learn-sync-head"><div><b>🔗 Aus Abgaben übernommen</b><div class="muted">${ts.length} gespeicherte ${ts.length===1?'Abgabe':'Abgaben'} werden automatisch analysiert und als Lernstoff verwendet.</div></div><button type="button" id="generatePracticeTest">📝 Probetest erstellen</button></div><div class="learn-sync-items">${ts.length?ts.map(t=>`<div class="learn-sync-item"><b>${esc(t.title)}</b><br><span class="muted">${esc(t.status||'')} ${t.date?'· '+esc(t.date.split('-').reverse().join('.')):''}${t.sourceFile?' · Quelle: '+esc(t.sourceFile):''}</span><div>${esc((t.description||'').slice(0,220))}${(t.description||'').length>220?'…':''}</div>${t.studyNotes?.length?`<details><summary><b>📚 Analysierter Lernstoff (${t.studyNotes.length})</b></summary><ul class="learn-sync-notes">${t.studyNotes.map(n=>`<li>${esc(n)}</li>`).join('')}</ul></details>`:''}</div>`).join(''):'<div class="muted">Noch keine Abgaben für dieses Fach gespeichert.</div>'}</div>`;
const next=document.getElementById('nextStudyEvent');if(next&&ts.length)next.textContent=nextDate(subject);
const packages=document.getElementById('studyPackages');if(packages&&ts.length){const staticItems=[...packages.querySelectorAll('.study-card')].filter(x=>!x.dataset.synced);packages.querySelectorAll('[data-synced="1"]').forEach(x=>x.remove());ts.forEach(t=>{const d=document.createElement('div');d.className='study-card';d.dataset.synced='1';d.textContent='📥 Abgabe als Lernstoff: '+t.title;packages.appendChild(d)})}
box?.querySelector('#generatePracticeTest')?.addEventListener('click',()=>showTest(subject));
}
function showTest(subject){let qs=buildQuestions(subject);if(!qs.length){alert('Für dieses Fach gibt es noch nicht genug gespeicherten Stoff.');return}qs=qs.sort(()=>Math.random()-.5).slice(0,Math.min(10,qs.length));const qbox=document.getElementById('studyQuestions');if(!qbox)return;qbox.innerHTML=`<div class="learn-sync-head"><div><h3 style="margin:0">📝 Probetest ${esc(subject)}</h3><div class="muted">${qs.length} Fragen automatisch aus deinen analysierten Abgaben.</div></div><button class="secondary" type="button" id="newPracticeTest">Neu mischen</button></div>`+qs.map((x,i)=>`<div class="learn-test-q"><b>${i+1}. ${esc(x.q)}</b><div class="muted">Quelle: ${esc(x.source)}</div><button class="secondary" type="button" data-test-answer="pt${i}">Lösung anzeigen</button><div class="learn-test-answer" id="pt${i}">${esc(x.a||'Für diese Frage ist noch keine Musterlösung gespeichert.')}</div></div>`).join('');qbox.querySelector('#newPracticeTest')?.addEventListener('click',()=>showTest(subject));qbox.querySelectorAll('[data-test-answer]').forEach(b=>b.onclick=()=>document.getElementById(b.dataset.testAnswer)?.classList.toggle('open'))}
const original=window.openStudySubject;window.openStudySubject=function(subject){const r=original?original(subject):undefined;setTimeout(()=>renderSubject(subject),0);return r};
window.addEventListener('quick-add-data-changed',()=>{const title=document.getElementById('studyTitle')?.textContent||'';const s=SUB.find(x=>title.includes(x));if(s)renderSubject(s)});
})();