(() => {
  const style=document.createElement('style');
  style.textContent=`
  .header-right{display:flex;flex-direction:column;align-items:stretch;gap:8px;min-width:190px}.header-right .student-name{text-align:center}.header-right .relax-footer{margin:0!important;padding:0!important;max-width:none!important;width:100%}.header-right .relax-inner{padding:7px 9px!important;border-radius:11px!important;gap:7px!important;flex-wrap:nowrap!important;box-shadow:0 7px 18px rgba(20,25,50,.16)!important}.header-right .relax-copy b{font-size:11px!important;white-space:nowrap}.header-right .relax-copy span{display:none!important}.header-right .relax-btn{padding:6px 8px!important;font-size:11px!important;border-radius:8px!important;white-space:nowrap}
  .commerce-news{max-width:1240px;margin:6px auto 18px;padding:0 24px}.commerce-news-panel{background:linear-gradient(145deg,#171b2d,#202844);border:1px solid rgba(148,163,184,.2);border-radius:22px;padding:20px;box-shadow:0 16px 40px rgba(31,42,68,.2);color:#eef2ff}.commerce-news-head{display:flex;justify-content:space-between;align-items:flex-start;gap:14px;flex-wrap:wrap;margin-bottom:16px}.commerce-news-title{display:flex;align-items:center;gap:10px}.commerce-news-mark{width:38px;height:38px;border-radius:12px;background:linear-gradient(135deg,#6d7cff,#27c4b8);display:grid;place-items:center;font-size:18px}.commerce-news-title h2{margin:0;font-size:20px}.commerce-news-title p{margin:3px 0 0;color:#a9b5ca;font-size:13px}.commerce-news-actions{display:flex;align-items:center;gap:10px;color:#a9b5ca;font-size:12px;flex-wrap:wrap}.commerce-news-refresh{border:1px solid rgba(255,255,255,.16);background:rgba(255,255,255,.07);color:#eef2ff;padding:8px 11px;border-radius:10px;font-weight:700;cursor:pointer}.commerce-news-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.commerce-news-card{display:flex;flex-direction:column;min-height:190px;background:linear-gradient(155deg,rgba(255,255,255,.08),rgba(255,255,255,.035));border:1px solid rgba(255,255,255,.1);border-radius:16px;padding:15px;text-decoration:none;color:#f8fafc;transition:.18s}.commerce-news-card:hover{transform:translateY(-2px);border-color:rgba(125,140,255,.55)}.commerce-news-meta{display:flex;justify-content:space-between;gap:8px;align-items:center;margin-bottom:11px}.commerce-news-tag{padding:5px 8px;border-radius:999px;background:rgba(91,108,255,.16);color:#cbd3ff;font-size:11px;font-weight:800}.commerce-news-date{font-size:11px;color:#98a5ba}.commerce-news-card h3{font-size:15px;line-height:1.35;margin:0 0 10px}.commerce-news-source{margin-top:auto;padding-top:12px;border-top:1px solid rgba(255,255,255,.08);display:flex;justify-content:space-between;color:#a9b5ca;font-size:12px}.commerce-news-arrow{font-size:16px;color:#91a0ff}.commerce-news-skeleton{height:190px;border-radius:16px;background:rgba(255,255,255,.06)}.commerce-news-error{grid-column:1/-1;padding:18px;border-radius:14px;background:rgba(255,255,255,.06);color:#cbd5e1}.commerce-news-badge{color:#8fe1d8}.commerce-news-dot{display:inline-block;width:7px;height:7px;border-radius:50%;background:#2dd4bf;margin-right:5px}@media(max-width:900px){.commerce-news-grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:850px){.header-right{align-self:flex-start;min-width:210px}}@media(max-width:620px){.commerce-news-grid{grid-template-columns:1fr}.commerce-news{padding:0 16px}.commerce-news-panel{padding:16px}.commerce-news-card{min-height:170px}}@media(prefers-reduced-motion:reduce){.commerce-news-card{transition:none!important}}
  `;
  document.head.appendChild(style);
  const footer=document.querySelector('.relax-footer'),student=document.querySelector('.student-name');
  if(footer&&student){const right=document.createElement('div');right.className='header-right';student.parentNode.insertBefore(right,student);right.appendChild(student);right.appendChild(footer)}
  const section=document.createElement('section');section.className='commerce-news';
  section.innerHTML=`<div class="commerce-news-panel"><div class="commerce-news-head"><div class="commerce-news-title"><div class="commerce-news-mark">🇦🇹</div><div><h2>E-Commerce News Österreich & Wien</h2><p>6 aktuelle Entwicklungen mit Fokus auf den österreichischen Onlinehandel und Wien</p></div></div><div class="commerce-news-actions"><span class="commerce-news-badge"><span class="commerce-news-dot"></span>automatisch aktuell</span><span id="commerceNewsUpdated">wird geladen …</span><button class="commerce-news-refresh" id="commerceNewsRefresh">↻ Aktualisieren</button></div></div><div class="commerce-news-grid" id="commerceNewsGrid">${'<div class="commerce-news-skeleton"></div>'.repeat(6)}</div></div>`;
  const home=document.getElementById('home');
  if(home) home.appendChild(section); else document.body.insertBefore(section,document.querySelector('script'));
  const grid=section.querySelector('#commerceNewsGrid'),updated=section.querySelector('#commerceNewsUpdated'),refresh=section.querySelector('#commerceNewsRefresh');
  const esc=(s='')=>String(s).replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const fd=x=>{try{return new Intl.DateTimeFormat('de-AT',{day:'2-digit',month:'2-digit',year:'numeric',timeZone:'Europe/Vienna'}).format(new Date(x))}catch{return''}};
  async function load(force=false){refresh.disabled=true;try{const r=await fetch('/api/news'+(force?'?t='+Date.now():''),{cache:force?'no-store':'default'});if(!r.ok)throw 0;const d=await r.json();if(!d.items||!d.items.length)throw 0;grid.innerHTML=d.items.map(n=>`<a class="commerce-news-card" href="${esc(n.url)}" target="_blank" rel="noopener noreferrer"><div class="commerce-news-meta"><span class="commerce-news-tag">${esc(n.icon||'🇦🇹')} ${esc(n.category||'Österreich')}</span><span class="commerce-news-date">${fd(n.publishedAt)}</span></div><h3>${esc(n.title)}</h3><div class="commerce-news-source"><span>${esc(n.source||'Quelle')}</span><span class="commerce-news-arrow">↗</span></div></a>`).join('');updated.textContent='Stand: '+new Intl.DateTimeFormat('de-AT',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit',timeZone:'Europe/Vienna'}).format(new Date(d.updatedAt))}catch{grid.innerHTML='<div class="commerce-news-error"><b>Österreich-News sind gerade nicht erreichbar.</b><br>Bitte später erneut versuchen.</div>';updated.textContent='vorübergehend offline'}finally{refresh.disabled=false}}
  refresh.addEventListener('click',()=>load(true));load();
  const modules=[['abgaben-module','assignment-tools.js'],['quick-add-module','quick-add.js'],['room-module','timetable-rooms.js'],['current-subject-module','current-subject.js'],['space-game-module','space-game.js'],['legacy-assignment-module','assignment-legacy-content.js'],['learning-fix-module','learning-fix.js'],['internet-search-module','internet-search.js'],['school-footer-module','school-footer.js'],['school-email-module','school-email.js'],['brainrot-module','brainrot.js'],['brainrot-audio-plus-module','brainrot-audio-plus.js'],['pigeon-audio-13-module','pigeon-audio-13.js'],['wallahi-link-module','wallahi-link.js']];
  modules.forEach(([key,src])=>{if(!document.querySelector(`script[data-${key}]`)){const s=document.createElement('script');s.src=src;s.defer=true;s.setAttribute(`data-${key}`,'1');document.body.appendChild(s)}});
})();