const TOPICS = [
  {category:'KI & Handel',icon:'✦',q:'(KI OR AI OR ChatGPT OR Agentic Commerce) (E-Commerce OR Onlinehandel) (Österreich OR Wien)'},
  {category:'Shopsysteme',icon:'▦',q:'(Shopify OR Shopware OR WooCommerce OR Odoo OR Shopsystem) (Österreich OR Wien)'},
  {category:'Marketing & SEO',icon:'⌕',q:'(Google OR SEO OR Online-Marketing OR Werbung OR Tracking) (E-Commerce OR Onlinehandel) (Österreich OR Wien)'},
  {category:'Social Commerce',icon:'◉',q:'(TikTok Shop OR Instagram OR Meta OR Social Commerce OR Influencer) (Österreich OR Wien)'},
  {category:'Payment & Logistik',icon:'↗',q:'(Payment OR PayPal OR Klarna OR Checkout OR Logistik OR Versand OR Paket) (E-Commerce OR Onlinehandel) Österreich'},
  {category:'Recht & EU',icon:'§',q:'(Gesetz OR Verbraucherrecht OR Datenschutz OR Barrierefreiheit OR Verpackung OR EU) (E-Commerce OR Onlinehandel) Österreich'},
  {category:'Markt & Trends',icon:'↗',q:'(E-Commerce OR Onlinehandel) (Studie OR Umsatz OR Trend OR Konsumenten OR Handel) (Österreich OR Wien)'}
];
const feedUrl=q=>'https://news.google.com/rss/search?q='+encodeURIComponent(q+' when:30d')+'&hl=de&gl=AT&ceid=AT:de';
function decodeXml(s=''){return s.replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g,'$1').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>')}
function stripHtml(s=''){return decodeXml(s).replace(/<[^>]*>/g,' ').replace(/\s+/g,' ').trim()}
function parseItems(xml,topic){const out=[];for(const block of xml.match(/<item>[\s\S]*?<\/item>/g)||[]){const get=tag=>{const m=block.match(new RegExp(`<${tag}(?:\\s[^>]*)?>([\\s\\S]*?)<\\/${tag}>`,'i'));return m?decodeXml(m[1]).trim():''};const title=stripHtml(get('title')),link=stripHtml(get('link')),pubDate=stripHtml(get('pubDate')),description=stripHtml(get('description'));const sm=block.match(/<source(?:\s+url="([^"]*)")?>([\s\S]*?)<\/source>/i);const source=sm?stripHtml(sm[2]):'News';if(!title||!link)continue;const cleanTitle=title.replace(/\s+-\s+[^-]{2,80}$/,'').trim()||title;const lower=`${cleanTitle} ${description} ${source}`.toLowerCase();let regionScore=0;if(/wien|vienna|wiener/.test(lower))regionScore+=8;if(/österreich|austria|österreichisch|wko|wirtschaftskammer|handelsverband/.test(lower))regionScore+=5;if(/eu|europäisch/.test(lower))regionScore+=1;out.push({title:cleanTitle,url:link,source,publishedAt:pubDate?new Date(pubDate).toISOString():null,category:topic.category,icon:topic.icon,regionScore})}return out}
module.exports=async function handler(req,res){try{const results=await Promise.all(TOPICS.map(async topic=>{const r=await fetch(feedUrl(topic.q),{headers:{'user-agent':'Mozilla/5.0 E-Commerce Dashboard Austria/1.0'}});if(!r.ok)return[];return parseItems(await r.text(),topic)}));const seen=new Set();const byTopic=results.map(list=>list.filter(x=>{const k=x.title.toLowerCase().replace(/[^a-z0-9äöüß]+/g,' ').trim();if(seen.has(k))return false;seen.add(k);return true}).sort((a,b)=>{const s=(b.regionScore||0)-(a.regionScore||0);return s||new Date(b.publishedAt||0)-new Date(a.publishedAt||0)}));let items=[];for(const list of byTopic){const local=list.find(x=>x.regionScore>=5)||list[0];if(local)items.push(local);if(items.length===6)break}if(items.length<6){const used=new Set(items.map(x=>x.title));const extras=byTopic.flat().filter(x=>!used.has(x.title)).sort((a,b)=>new Date(b.publishedAt||0)-new Date(a.publishedAt||0));items.push(...extras.slice(0,6-items.length))}items=items.slice(0,6).map(({regionScore,...x})=>x);res.setHeader('Cache-Control','s-maxage=1800, stale-while-revalidate=3600');res.status(200).json({updatedAt:new Date().toISOString(),region:'Österreich / Wien',diverseTopics:true,items})}catch(err){res.status(500).json({error:'News konnten momentan nicht geladen werden.',items:[]})}};